version: '3'

services:
  mysql:
    image: mysql:latest
    ports:
      - "3333:3306"
    volumes:
      - ./catalog-data:/var/lib/mysql
    networks:
      main:
        aliases:
          - mysql.docker
    environment:
      - MYSQL_ROOT_PASSWORD=toor

  catalog:
    image: catalog-dev
    ports:
      - "4444:4848"
      - "8585:8080"
    links:
      - mysql
    depends_on:
      - mysql
    networks:
      main:
        aliases:
          - catalog.docker
    volumes:
      - ../:/catalog

networks:
  main:
    external: true
